// <auto-generated />
using System;
using A_DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace A_DAL.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("A_DAL.Models.QuizChitiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiemToida")
                        .HasColumnType("int")
                        .HasColumnName("MaxGrade");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("Datetime")
                        .HasColumnName("Ketthuc");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenQuiz");

                    b.Property<int>("SoluongCauhoi")
                        .HasColumnType("int")
                        .HasColumnName("Socauhoi");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("Datetime")
                        .HasColumnName("Batdau");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("Trangthai");

                    b.HasKey("Id");

                    b.ToTable("QuizChitiet", (string)null);
                });

            modelBuilder.Entity("A_DAL.Models.Sinhvien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chuyennganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ChuyenNganh");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EmailSV");

                    b.Property<string>("MaSv")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MaSV");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenSV");

                    b.Property<string>("Nganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nganh");

                    b.HasKey("Id");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("A_DAL.Models.SinhvienLamQuiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdQuizChitiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSV")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Result")
                        .HasColumnType("float");

                    b.Property<DateTime>("TakeQuizTime")
                        .HasColumnType("Datetime");

                    b.HasKey("Id");

                    b.HasIndex("IdQuizChitiet");

                    b.HasIndex("IdSV");

                    b.ToTable("SinhvienLamQuiz");
                });

            modelBuilder.Entity("A_DAL.Models.SinhvienLamQuiz", b =>
                {
                    b.HasOne("A_DAL.Models.QuizChitiet", "QuizChitiet")
                        .WithMany()
                        .HasForeignKey("IdQuizChitiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_DAL.Models.Sinhvien", "Sinhvien")
                        .WithMany()
                        .HasForeignKey("IdSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizChitiet");

                    b.Navigation("Sinhvien");
                });
#pragma warning restore 612, 618
        }
    }
}
